# Generated by Django 4.1.5 on 2024-04-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovies', '0002_movie_is_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rented_to',
        ),
        migrations.AddField(
            model_name='rental',
            name='rented_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
