# Generated by Django 4.1.5 on 2024-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovies', '0003_remove_rental_rented_to_rental_rented_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rented_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
