# Generated by Django 4.1.5 on 2024-04-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovies', '0004_rental_rented_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rented_on',
        ),
        migrations.AlterField(
            model_name='rental',
            name='rented_to',
            field=models.CharField(max_length=100),
        ),
    ]
