# Generated by Django 4.1.5 on 2024-04-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovies', '0005_remove_rental_rented_on_alter_rental_rented_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rented_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
