# Generated by Django 4.1.5 on 2024-04-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMovies', '0008_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
